"""Stage: explain — global and per-zip SHAP explanations (task M5).

`run(config)` writes a global SHAP summary plot (reports/figures/shap_summary.png)
and reports/explanations.md (top-k features + DRAFT plain-English interpretations
for the team). `explain_zip(zip, month, config)` returns the top-k signed feature
contributions for one zip-month in < 1s, using a module-cached TreeExplainer and
a cached copy of the feature panel so the dashboard can call it interactively.

SHAP additivity (exact for trees under the identity link used by
reg:squarederror): expected_value + sum(contributions) == model prediction.
"""

import matplotlib

matplotlib.use("Agg")  # headless backend, before shap/pyplot pull in matplotlib
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import shap  # noqa: E402

from model.evaluate import _drop_flagged  # noqa: E402
from model.io import figures_dir, model_config, models_dir, reports_dir  # noqa: E402
from pipeline.io_utils import REPO_ROOT, get_logger  # noqa: E402

log = get_logger("explain")

_CACHE: dict = {}
GLOBAL_SAMPLE = 8000  # rows for the global summary (TreeExplainer is exact + fast)


def _point_artifact(config: dict):
    path = models_dir(config) / "xgb_point.joblib"
    if not path.exists():
        raise RuntimeError(f"{path.name} missing. Run `python -m model train` first.")
    import joblib

    return joblib.load(path)


def get_explainer(config: dict):
    """Cached TreeExplainer + model + feature columns (built once per process)."""
    if "explainer" not in _CACHE:
        art = _point_artifact(config)
        _CACHE["model"] = art["model"]
        _CACHE["feat_cols"] = art["feature_cols"]
        _CACHE["explainer"] = shap.TreeExplainer(art["model"])
    return _CACHE["explainer"]


def _features(config: dict) -> pd.DataFrame:
    if "features" not in _CACHE:
        _CACHE["features"] = pd.read_parquet(
            REPO_ROOT / config["paths"]["processed"] / "features.parquet"
        )
    return _CACHE["features"]


def top_contributions(shap_row: np.ndarray, feat_cols: list[str], k: int) -> pd.Series:
    """Top-k features by absolute SHAP contribution for one row (signed values)."""
    s = pd.Series(np.asarray(shap_row, dtype=float), index=feat_cols)
    return s.reindex(s.abs().sort_values(ascending=False).index).head(k)


def explain_zip(zip_code: str, month, config: dict, k: int | None = None) -> dict:
    """Top-k signed SHAP contributions for one (zip, month). Fast after warm cache."""
    explainer = get_explainer(config)
    feat_cols = _CACHE["feat_cols"]
    k = k or model_config(config)["top_k_shap_features"]
    feats = _features(config)
    row = feats[(feats["zip"] == str(zip_code)) & (feats["month"] == pd.Timestamp(month))]
    if row.empty:
        raise RuntimeError(f"No feature row for zip {zip_code} at {month}.")
    X = row[feat_cols]
    sv = np.asarray(explainer.shap_values(X), dtype=float)[0]
    expected = float(np.ravel(explainer.expected_value)[0])
    prediction = float(_CACHE["model"].predict(X)[0])
    return {
        "zip": str(zip_code),
        "month": pd.Timestamp(month).strftime("%Y-%m"),
        "expected_value": expected,
        "prediction": prediction,
        "contributions": top_contributions(sv, feat_cols, k),
    }


def _write_explanations(mean_abs: pd.Series, config: dict, fig_rel: str) -> None:
    k = model_config(config)["top_k_shap_features"]
    top = mean_abs.sort_values(ascending=False).head(k)
    lines = [
        "# SHAP explanations",
        "",
        "> **DRAFT — team must write the interpretations.** The rankings and numbers "
        "are generated; the plain-English \"what this means\" column is the team's "
        "intellectual contribution and must be written in your own words.",
        "",
        f"_Generated by `python -m model explain`. Global importance = mean absolute "
        f"SHAP value over a {GLOBAL_SAMPLE:,}-row train-split sample (flagged rows "
        f"excluded). SHAP is exact for trees; contributions add up to the prediction._",
        "",
        f"![global SHAP summary]({fig_rel.split('/')[-1]})",
        "",
        f"## Top {k} features by global importance",
        "",
        "| rank | feature | mean \\|SHAP\\| | plain-English interpretation (TEAM) |",
        "|---|---|---|---|",
    ]
    for i, (feat, val) in enumerate(top.items(), 1):
        lines.append(f"| {i} | `{feat}` | {val:.5f} | _<!-- TEAM: what does this feature mean and why does it matter for 3-month price change? -->_ |")
    lines += [
        "",
        "<!-- TEAM: replace each interpretation cell above. Example shape: "
        "'`price_mom_3m` — recent short-term momentum; zips already rising tend to "
        "keep rising over the next quarter (with mean-reversion caveats).' Keep it "
        "defensible in Q&A. -->",
        "",
    ]
    path = reports_dir(config) / "explanations.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    log.info("wrote %s", path.relative_to(REPO_ROOT))


def run(config: dict) -> None:
    explainer = get_explainer(config)
    feat_cols = _CACHE["feat_cols"]
    seed = model_config(config)["random_seed"]
    feats = _features(config)
    train = _drop_flagged(feats[feats["split"] == "train"], config)
    sample = train.sample(n=min(GLOBAL_SAMPLE, len(train)), random_state=seed)
    X = sample[feat_cols]
    log.info("computing SHAP on %d sampled train rows (%d features)", len(X), len(feat_cols))
    sv = np.asarray(explainer.shap_values(X), dtype=float)

    # Global summary plot.
    plt.figure()
    shap.summary_plot(sv, X, show=False, plot_size=(9, 6), max_display=15)
    fig = plt.gcf()
    fig.suptitle("Global SHAP feature importance (train sample)", y=1.02, fontsize=11)
    fig.axes[-1].set_xlabel("SHAP value (impact on predicted 3-month price change)")
    fig_path = figures_dir(config) / "shap_summary.png"
    fig.savefig(fig_path, dpi=130, bbox_inches="tight")
    plt.close(fig)
    fig_rel = str(fig_path.relative_to(REPO_ROOT)).replace("\\", "/")
    log.info("wrote %s", fig_rel)

    mean_abs = pd.Series(np.abs(sv).mean(axis=0), index=feat_cols)
    _write_explanations(mean_abs, config, fig_rel)
